-- Create units table
CREATE TABLE IF NOT EXISTS public.units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    code TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add some common units
INSERT INTO public.units (name_ar, name_en, code) VALUES
('كيلوجرام', 'Kilogram', 'KG'),
('جرام', 'Gram', 'G'),
('لتر', 'Liter', 'L'),
('متر', 'Meter', 'M'),
('قطعة', 'Piece', 'PC'),
('علبة', 'Box', 'BOX'),
('كرتونة', 'Carton', 'CARTON')
ON CONFLICT (code) DO NOTHING;
